server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: sectors
          uri: lb://sectors-service
          predicates:
            - Path=/api/sectors/**
        - id: classes
          uri: lb://classes-service
          predicates:
            - Path=/api/classes/**
